repos:
-   repo: https://github.com/mwouts/jupytext
    rev: v1.9.1
    hooks:
    - id: jupytext
      args: [--from, ipynb, --pipe, black, --check, flake8]
      additional_dependencies:
        - black==20.8b1 # Matches hook
-   repo: https://github.com/ambv/black
    rev: "20.8b1"
    hooks:
    - id: black
      language_version: python3
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: flake8