version: '2.3'
services:
  python:
    #build: ./
    image: pydev-poetry
    container_name: pydev-poetry-jupyter
    volumes:
      - ./:/workspaces
      - ~/dataset:/dataset
  
  jupyter:
    #build: ./
    image: pydev-poetry
    container_name: pydev-poetry-jupyter
    volumes:
      - ./:/workspaces
      - ~/dataset:/dataset
    ports:
      - "8888:8888"
    command: /bin/bash -c "poetry run jupyter notebook --notebook-dir /workspaces --ip=0.0.0.0 --allow-root"

  lab:
    #build: ./
    image: pydev-poetry
    container_name: pydev-poetry-lab
    volumes:
      - ./:/workspaces
      - ~/dataset:/dataset
    ports:
      - "8888:8888"
    command: /bin/bash -c "poetry run jupyter lab --notebook-dir /workspaces --ip=0.0.0.0 --allow-root"

  lab-gpu:
    #build: ./
    image: pydev-poetry
    shm_size: '2gb'
    container_name: pydev-poetry-lab-gpu
    runtime: nvidia
    volumes:
      - ./:/workspaces
    ports:
      - "8889:8889"
    command: /bin/bash -c "poetry run jupyter lab --notebook-dir /workspaces --port 8889 --ip=0.0.0.0 --allow-root"

