version: '2.3'
services:
  python:
    build: ./
    container_name: pydev-poetry-jupyter
    volumes:
      - ./:/workspace
      - ~/dataset:/dataset
  
  jupyter:
    build: ./
    container_name: pydev-poetry-jupyter
    volumes:
      - ./:/workspace
      - ~/dataset:/dataset
    ports:
      - "8888:8888"
    command: jupyter notebook --notebook-dir /workspace --ip=0.0.0.0 --allow-root

  lab:
    build: ./
    container_name: pydev-poetry-lab
    volumes:
      - ./:/workspace
      - ~/dataset:/dataset
    ports:
      - "8888:8888"
    command: jupyter lab --notebook-dir /workspace --ip=0.0.0.0 --allow-root

  lab-gpu:
    build: ./
    shm_size: '2gb'
    container_name: pydev-poetry-lab-gpu
    runtime: nvidia
    volumes:
      - ./:/workspace
    ports:
      - "8889:8889"
    command: jupyter lab --notebook-dir /workspace --port 8889 --ip=0.0.0.0

